server:
  port: 3344


spring:
  application:
    name: cloud-config-file
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zengquan1314/springboot-colud.git
          #search-paths:
           #   - springboot-colud   #如果git仓库中有文件夹目录。。这就是对应文件夹目录
          username: zengquan1314  #git的账号
          password: zengquan1998  #git的密码
      label: main                 #git的分之文件名
  #RabbitMQ的相关配置#
  rabbitmq:
    host: localhost #RabbitMQ的本机地址
    port: 5672  #RabbitMQ对外抛出的端口号
    username: guest #RabbitMQ的用户账号
    password: guest #RabbitMQ的用户密码


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: config-file-3344
    prefer-ip-address: true     #访问路径可以显示IP地址

##RabbitMQ相关配置，暴露Bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"
