server:
  port: 90
spring:
  application:
    name: cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr:  localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'


server_url:
  url: "http://cloud-nacos"
